<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>sDiceTutor | Edit Profile</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
  <!-- daterange picker -->
  <link rel="stylesheet" href="../../plugins/daterangepicker/daterangepicker.css">
  <!-- iCheck for checkboxes and radio inputs -->
  <link rel="stylesheet" href="../../plugins/icheck-bootstrap/icheck-bootstrap.min.css">
  <!-- Bootstrap Color Picker -->
  <link rel="stylesheet" href="../../plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <link rel="stylesheet" href="../../plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
  <!-- Select2 -->
  <link rel="stylesheet" href="../../plugins/select2/css/select2.min.css">
  <link rel="stylesheet" href="../../plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
  <!-- Bootstrap4 Duallistbox -->
  <link rel="stylesheet" href="../../plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css">
  <!-- BS Stepper -->
  <link rel="stylesheet" href="../../plugins/bs-stepper/css/bs-stepper.min.css">
  <!-- dropzonejs -->
  <link rel="stylesheet" href="../../plugins/dropzone/min/dropzone.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini" style="background-color:#F5F5F5;">
<div class="wrapper" >
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light" >
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="../../index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4" style="position:fixed;">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
      <img src="../../dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">DiceTutors</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="../../dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Alexander Pierce</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2" style="position:fixed; background-color:#000000;">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false" >
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item" >
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Profile
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="../../index.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p> Edit Profile</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="../../index2.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Photo Upload</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="../../index3.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Bank Details</p>
                </a>
              </li>
			   <li class="nav-item">
                <a href="../../index3.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Accunt Verifiacation</p>
                </a>
              </li>
            </ul>
          </li>
         
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Update Profile</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Session</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content" style="background-color:#E1F0F0;>
          <form>
          <!-- /.card-header -->
		  <div class="col-sm-15 col-sm-offset-16" style="background-color:#E1F0F0;>
          <div class="card-body" style="background-color:#E1F0F0;>
            <div class="row"  >
              <div class="col-6 col-sm-6" style="position:absolute; left:400px;">
			
             <div class="form-group"  >
                 <label>Full Name</label>
                 <div class="form-group">
                    <input type="text" class="form-control" name="name" required placeholder=''">
                  </div>
             </div>
				
			<div class="form-group"  >
                 <label>Email Address</label>
                 <div class="form-group">
                    <input type="text" class="form-control" name="email" required placeholder=''">
                  </div>
             </div>
			 <div class="form-group"  >
                 <label>I am.</label>
                 <div class="form-group">
				    <div class="col-3 col-sm-6">
                    <select class="form-control" required name="gender" >
                    <option selected="selected">Select Gender</option>
                    <option value="Male">Male</option>
                    <option value="Female">Female</option>
                  </select>
				  </div>
                  </div>
             </div>
		     <div class="form-group"  >
			      <label style="font-family:'Courier New', Courier, monospace;"><b style="color:#FF0000; font-size:20px;">Current Location</b> <br>Enter your current location. This should be the address where you reside or live. If you move to a new location, you must update it here. Please write it properly.</label>
				  <label>Street Address</label>  
                 <div class="form-group">
                    <input type="text" class="form-control" name="address" required placeholder="E.g 28 Saint John Street Gowon Estate Ipaja"">
                  </div>
             </div>
			 <br>
	      	 <div class="form-inline">
            <div class="form-group">
                <div><label>Town or City</label></div>
                <input type="text" name="vicinity" maxlength="80" value="" class="form-control" placeholder="E.g. Ipaja" required="true">
            <div class="form-group">
                <div><label>State</label></div>
                    <select name="state" class="form-control"  placeholder="Input your state" required="true">
  <option value="" selected=""><?php echo $state ; ?></option>

  <option value="Abia">Abia</option>

  <option value="Abuja">Abuja</option>

  <option value="Adamawa">Adamawa</option>

  <option value="Akwa Ibom">Akwa Ibom</option>

  <option value="Anambra">Anambra</option>

  <option value="Bayelsa">Bayelsa</option>

  <option value="Bauchi">Bauchi</option>

  <option value="Benue">Benue</option>

  <option value="Borno">Borno</option>

  <option value="Cross River">Cross River</option>

  <option value="Delta">Delta</option>

  <option value="Edo">Edo</option>

  <option value="Ebonyi">Ebonyi</option>

  <option value="Ekiti">Ekiti</option>

  <option value="Enugu">Enugu</option>

  <option value="Gombe">Gombe</option>

  <option value="Imo">Imo</option>

  <option value="Jigawa">Jigawa</option>

  <option value="Kaduna">Kaduna</option>

  <option value="Kano">Kano</option>

  <option value="Katsina">Katsina</option>

  <option value="Kebbi">Kebbi</option>

  <option value="Kogi">Kogi</option>

  <option value="Kwara">Kwara</option>

  <option value="Lagos">Lagos</option>

  <option value="Nassarawa">Nassarawa</option>

  <option value="Niger">Niger</option>

  <option value="Ogun">Ogun</option>

  <option value="Ondo">Ondo</option>

  <option value="Osun">Osun</option>

  <option value="Oyo">Oyo</option>

  <option value="Plateau">Plateau</option>

  <option value="Rivers">Rivers</option>

  <option value="Sokoto">Sokoto</option>

  <option value="Taraba">Taraba</option>

  <option value="Yobe">Yobe</option>

  <option value="Zamfara">Zamfara</option>

</select>
</div>
             </div>
			 </div>
			 <br>
				<div class="col-12 col-sm-12">
                     <div class="form-group">
                        <label style="font-family:'Courier New', Courier, monospace;">Describe Yourself to the Dice Tutors Community</label>
                        <textarea class="form-control" name="description" rows="5"  placeholder="max 400 word"></textarea>
                      </div>
                </div>
				<label style="font-size:25px; font-family:Verdana, Arial, Helvetica, sans-serif; color:#FF0000;">Credentials</label>
				 <div class="form-group"  >
                  <label><b style="color:#CC3366; font-size:20px;">Education</b> <br><b style="font-family:'Courier New', Courier, monospace;">
Enter your highest educational qualifications, whether in-view or completed. Please write in full, no abbreviations. E.g. write 'University of Lagos' not 'UNILAG' </label>
                 <label>Name of School or Institute</label></b>
				 <div class="form-group">
                    <input type="text" class="form-control" name="name" required placeholder=''">
                  </div>
             </div>
			   <div class="row row-space-2">
                            <div class="col-sm-6">
                                <div class="form-group ">
                                    <label class="pad-down-5">Course of Study</label>
                                    <label class="sr-only">Course</label>
                                    <input type="text" name="course" value="" maxlength="125" class="form-control">
                                    
                             </div>
                         </div>
                         <div class="col-sm-6">
                            <div class="form-group ">
                                <label class="pad-down-5">Degree</label>
                                <label class="sr-only">Degree</label>
                                <select name="degree" class="form-control" >
  <option value=" <?php echo $degree ; ?>" selected=""></option>

  <option value="B.Sc.">B.Sc.</option>

  <option value="B.A.">B.A.</option>

  <option value="B.Ed.">B.Ed.</option>

  <option value="B.Eng.">B.Eng.</option>

  <option value="B.Tech.">B.Tech.</option>

  <option value="Diploma">Diploma</option>

  <option value="MBBS">MBBS</option>

  <option value="HND">HND</option>

  <option value="OND">OND</option>

  <option value="M.Sc.">M.Sc.</option>

  <option value="LL.B">LL.B</option>

  <option value="MBA">MBA</option>

  <option value="PhD">PhD</option>

  <option value="N.C.E">N.C.E</option>

  <option value="S.S.C.E">S.S.C.E</option>

</select>
</div>
</div>
</div>

                <label> <div class="padding-bottom-25">
				<label style="color:#CC3366; font-size:20px;">Work Experience</label><br><b style="font-family:'Courier New', Courier, monospace;">
                Enter your most recent work experience if any, and indicate if you currently work there. Please note that you may be required to provide proof.
				<br>
            </div></label></b>
                  <br>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group ">
                                <label class="pad-down-5">Name of Company or Organization</label>
                                <label class="sr-only">Organization Name</label>
                                <input type="text" name="workexperience" value="" maxlength="125" class="form-control">
                                
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group ">
                                <label class="pad-down-5">Your Role</label>
                                <label class="sr-only">Role</label>
                                <input type="text" name="role" value="" maxlength="125" class="form-control" >
                                
                            </div>
                        </div>
						</div>
				 <div class="form-group">
                 <label>I currently work there</label>
                 <div class="form-group">
				    <div class="col-12 col-sm-12">
                    <select class="form-control" required name="current_work" >
                    <option selected="selected">Select Option</option>
                    <option value="Yes">Yes</option>
                    <option value="No">No</option>
                  </select>
				  </div>
                  </div>
             </div>
			 
        <label style="color:#CC3366; font-size:20px;">
            Teaching Experience
        </label><br>

        <div class="col-md-12">
            <div class="row row-space-bottom-5">
                <label class="col-md-3 text-right margin-bottom-5" style="font-family:'Courier New', Courier, monospace;">
                    How long have you been teaching?
                </label>
                <div class="col-md-9">
                    <select name="teaching" class="form-control" id="id_years_of_teaching" data-parsley-id="2043">
  <option value="" selected=""> How Long</option>

  <option value="Less than 2 years">Less than 2 years</option>

  <option value="Between 3 to 5 years">Between 3 to 5 years</option>

  <option value="Between 6 to 10 years">Between 6 to 10 years</option>

  <option value="More than 10 years">More than 10 years</option>

</select>
      </div>
   </div>
    <div class="form-group">
                 <label style="color:#CC3366; font-size:20px;">Academic Curriculum</label><br><b style="font-family:'Courier New', Courier, monospace;">

If you teach academic subjects for nursery, primary or secondary, then select the curriculum you can teach with. Skip this if you teach non-academic subjects or skills. </label></b>
                 <div class="form-group">
				    <div class="col-12 col-sm-12">
                    <select class="form-control" required name="current_work" >
                    <option selected="selected">Select Option</option>
                    <option value="Nigeria">Nigeria</option>
                    <option value="British">British</option>
					<option value="American">American</option>
                    <option value="Montessori">Montessori</option>
                  </select>
				  </div>
                  </div>
				  	<div class="col-12 col-sm-12">
                     <div class="form-group">
                         <label style="color:#CC3366; font-size:15px;">Introduce Yourself to Clients <div style="background-color:#33CCCC;"></label><br><b style="font-family:'Courier New', Courier, monospace; height:500px; padding-left:10px; vertical-align:text-top; text-align:center; text-indent:inherit;">

Your tutor profile is your best opportunity to "sell yourself" as a tutor on Tuteria. Students often look at multiple tutor profiles before selecting a tutor to contact, so you need to be thorough, yet concise in describing your tutoring abilities, qualifications, experience and teaching style.

Follow these important guidelines
Write at least 2-4 paragraphs describing your tutoring and teaching qualifications and experience. Be sure to include any awards or trainings you’ve received that support your teaching credentials.Outline the subjects you specialize in and explain your teaching method. Include any degrees or awards that make you standout and qualified to teach those subjects or skills. Write as though you are talking to the client directly and encourage them to book a lesson with you.

</label></b></div>
                        <textarea class="form-control" name="selfdescription" rows="5" height="120"  placeholder="max 400 word"></textarea>
                      </div>
                </div>
				 <div class="col-sm-12 col-sm-offset-9" align="right">
					  <input type="submit" name="submit"  class="btn btn-primary btn-lg" value="Submit Profile">
					  
                </div>
   
   <br> <br> 
                 

				
		  </div> </div> </div>
		  </form>
  
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="../../plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Select2 -->
<script src="../../plugins/select2/js/select2.full.min.js"></script>
<!-- Bootstrap4 Duallistbox -->
<script src="../../plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js"></script>
<!-- InputMask -->
<script src="../../plugins/moment/moment.min.js"></script>
<script src="../../plugins/inputmask/jquery.inputmask.min.js"></script>
<!-- date-range-picker -->
<script src="../../plugins/daterangepicker/daterangepicker.js"></script>
<!-- bootstrap color picker -->
<script src="../../plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="../../plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Bootstrap Switch -->
<script src="../../plugins/bootstrap-switch/js/bootstrap-switch.min.js"></script>
<!-- BS-Stepper -->
<script src="../../plugins/bs-stepper/js/bs-stepper.min.js"></script>
<!-- dropzonejs -->
<script src="../../plugins/dropzone/min/dropzone.min.js"></script>
<!-- AdminLTE App -->
<script src="../../dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="../../dist/js/demo.js"></script>
<!-- Page specific script -->
<script>
  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
      theme: 'bootstrap4'
    })

    //Datemask dd/mm/yyyy
    $('#datemask').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' })
    //Datemask2 mm/dd/yyyy
    $('#datemask2').inputmask('mm/dd/yyyy', { 'placeholder': 'mm/dd/yyyy' })
    //Money Euro
    $('[data-mask]').inputmask()

    //Date picker
    $('#reservationdate').datetimepicker({
        format: 'L'
    });

    //Date and time picker
    $('#reservationdatetime').datetimepicker({ icons: { time: 'far fa-clock' } });

    //Date range picker
    $('#reservation').daterangepicker()
    //Date range picker with time picker
    $('#reservationtime').daterangepicker({
      timePicker: true,
      timePickerIncrement: 30,
      locale: {
        format: 'MM/DD/YYYY hh:mm A'
      }
    })
    //Date range as a button
    $('#daterange-btn').daterangepicker(
      {
        ranges   : {
          'Today'       : [moment(), moment()],
          'Yesterday'   : [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
          'Last 7 Days' : [moment().subtract(6, 'days'), moment()],
          'Last 30 Days': [moment().subtract(29, 'days'), moment()],
          'This Month'  : [moment().startOf('month'), moment().endOf('month')],
          'Last Month'  : [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        startDate: moment().subtract(29, 'days'),
        endDate  : moment()
      },
      function (start, end) {
        $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'))
      }
    )

    //Timepicker
    $('#timepicker').datetimepicker({
      format: 'LT'
    })

    //Bootstrap Duallistbox
    $('.duallistbox').bootstrapDualListbox()

    //Colorpicker
    $('.my-colorpicker1').colorpicker()
    //color picker with addon
    $('.my-colorpicker2').colorpicker()

    $('.my-colorpicker2').on('colorpickerChange', function(event) {
      $('.my-colorpicker2 .fa-square').css('color', event.color.toString());
    })

    $("input[data-bootstrap-switch]").each(function(){
      $(this).bootstrapSwitch('state', $(this).prop('checked'));
    })

  })
  // BS-Stepper Init
  document.addEventListener('DOMContentLoaded', function () {
    window.stepper = new Stepper(document.querySelector('.bs-stepper'))
  })

  // DropzoneJS Demo Code Start
  Dropzone.autoDiscover = false

  // Get the template HTML and remove it from the doumenthe template HTML and remove it from the doument
  var previewNode = document.querySelector("#template")
  previewNode.id = ""
  var previewTemplate = previewNode.parentNode.innerHTML
  previewNode.parentNode.removeChild(previewNode)

  var myDropzone = new Dropzone(document.body, { // Make the whole body a dropzone
    url: "/target-url", // Set the url
    thumbnailWidth: 80,
    thumbnailHeight: 80,
    parallelUploads: 20,
    previewTemplate: previewTemplate,
    autoQueue: false, // Make sure the files aren't queued until manually added
    previewsContainer: "#previews", // Define the container to display the previews
    clickable: ".fileinput-button" // Define the element that should be used as click trigger to select files.
  })

  myDropzone.on("addedfile", function(file) {
    // Hookup the start button
    file.previewElement.querySelector(".start").onclick = function() { myDropzone.enqueueFile(file) }
  })

  // Update the total progress bar
  myDropzone.on("totaluploadprogress", function(progress) {
    document.querySelector("#total-progress .progress-bar").style.width = progress + "%"
  })

  myDropzone.on("sending", function(file) {
    // Show the total progress bar when upload starts
    document.querySelector("#total-progress").style.opacity = "1"
    // And disable the start button
    file.previewElement.querySelector(".start").setAttribute("disabled", "disabled")
  })

  // Hide the total progress bar when nothing's uploading anymore
  myDropzone.on("queuecomplete", function(progress) {
    document.querySelector("#total-progress").style.opacity = "0"
  })

  // Setup the buttons for all transfers
  // The "add files" button doesn't need to be setup because the config
  // `clickable` has already been specified.
  document.querySelector("#actions .start").onclick = function() {
    myDropzone.enqueueFiles(myDropzone.getFilesWithStatus(Dropzone.ADDED))
  }
  document.querySelector("#actions .cancel").onclick = function() {
    myDropzone.removeAllFiles(true)
  }
  // DropzoneJS Demo Code End
</script>
</body>
</html>
